# Generated by Django 6.0.7 on 2026-09-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_id', models.IntegerField(db_index=True)),
                ('uploaded_by', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('blockchain_status', models.CharField(choices=[('Pending', 'Pending Registration'), ('Registered', 'Registered'), ('Failed', 'Registration Failed')], default='Pending', max_length=20)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_registered_at', models.DateTimeField(blank=True, null=True)),
                ('integrity_status', models.CharField(choices=[('Not Verified', 'Not Verified'), ('Verified', 'Verified'), ('Failed', 'Integrity Check Failed')], default='Not Verified', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evidence',
            },
        ),
    ]
