# Generated by Django 6.0.7 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('document_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_network', models.CharField(blank=True, max_length=100, null=True)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=30, null=True)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'blockchain_logs',
                'managed': False,
            },
        ),
    ]
