# Generated by Django 6.0.7 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('hearing_id', models.AutoField(primary_key=True, serialize=False)),
                ('resident_id', models.IntegerField()),
                ('complaint_id', models.IntegerField()),
                ('case_number', models.CharField(max_length=50)),
                ('complainant_name', models.CharField(max_length=150)),
                ('respondent_name', models.CharField(max_length=150)),
                ('dispute_nature', models.CharField(max_length=150)),
                ('hearing_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('chamber', models.CharField(max_length=100)),
                ('mediator', models.CharField(blank=True, max_length=150, null=True)),
                ('summons_status', models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Served', 'Served')], default='Pending', max_length=20)),
                ('hearing_stage', models.CharField(choices=[('Mediation', 'Mediation'), ('Conciliation', 'Conciliation'), ('Pangkat', 'Pangkat'), ('Arbitration', 'Arbitration'), ('Settlement', 'Settlement')], default='Mediation', max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Postponed', 'Postponed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hearings',
                'ordering': ['hearing_date', 'start_time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HearingAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('attachment_type', models.CharField(choices=[('Audio Recording', 'Audio Recording'), ('Document', 'Document'), ('Image', 'Image'), ('Hearing Minutes', 'Hearing Minutes'), ('Other', 'Other')], default='Document', max_length=30)),
                ('file', models.FileField(upload_to='hearing_attachments/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=150, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('uploaded_by', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hearing_attachments',
                'ordering': ['-uploaded_at', '-attachment_id'],
                'managed': False,
            },
        ),
    ]
