# Generated by Django 6.0.7 on 2026-10-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearingmodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingMinutesDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('hearing_id', models.IntegerField(db_index=True)),
                ('complaint_id', models.IntegerField(db_index=True)),
                ('document_type', models.CharField(default='HEARING_MINUTES', max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('blockchain_status', models.CharField(default='Pending', max_length=20)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_registered_at', models.DateTimeField(blank=True, null=True)),
                ('integrity_status', models.CharField(default='Not Verified', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hearing_minutes_documents',
                'ordering': ['-generated_at', '-document_id'],
            },
        ),
    ]
