# Generated by Django 6.0.7 on 2026-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearingmodule', '0002_hearingminutesdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='hearingminutesdocument',
            name='processed_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hearingminutesdocument',
            name='processed_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hearingminutesdocument',
            name='processed_by_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
