# Generated by Django 6.0.7 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(db_column='audit_id', primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True)),
                ('action', models.CharField(db_column='action', max_length=100)),
                ('module', models.CharField(db_column='module', max_length=100)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('ip_address', models.CharField(blank=True, db_column='ip_address', max_length=45, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at', '-audit_id'],
                'managed': False,
            },
        ),
    ]
