# Generated by Django 6.0.7 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('resident_id', models.IntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('request_notes', models.TextField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Verification', 'Under Verification'), ('Ready for Signature', 'Ready for Signature'), ('Ready for Pickup', 'Ready for Pickup'), ('Released', 'Released'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=50)),
                ('submitted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_requests',
                'ordering': ['-submitted_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_types',
                'managed': False,
            },
        ),
    ]
