# Generated by Django 6.0.7 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('document_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('qr_code', models.CharField(blank=True, max_length=500, null=True)),
                ('issued_by', models.IntegerField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'document_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplaintDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_id', models.IntegerField(db_index=True)),
                ('document_type', models.CharField(default='COMPLAINT', max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64)),
                ('blockchain_status', models.CharField(choices=[('Pending', 'Pending Registration'), ('Registered', 'Registered'), ('Failed', 'Registration Failed')], default='Pending', max_length=20)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_registered_at', models.DateTimeField(blank=True, null=True)),
                ('integrity_status', models.CharField(choices=[('Not Verified', 'Not Verified'), ('Verified', 'Verified'), ('Failed', 'Integrity Check Failed')], default='Not Verified', max_length=20)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complaint_documents',
            },
        ),
    ]
