# Generated by Django 6.0.7 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resident_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('civil_status', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('house_block_lot', models.CharField(blank=True, max_length=100, null=True)),
                ('street_purok_sitio', models.CharField(blank=True, max_length=150, null=True)),
                ('province', models.CharField(max_length=100)),
                ('municipality_city', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('verification_status', models.CharField(default='Pending', max_length=30)),
                ('verified_by', models.IntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'residents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('role', models.CharField(default='Resident', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
