# Generated by Django 6.0.7 on 2026-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('resident_id', models.IntegerField()),
                ('report_type', models.CharField(choices=[('Formal Complaint', 'Formal Complaint'), ('Community Issue', 'Community Issue')], default='Formal Complaint', max_length=30)),
                ('complaint_type', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.TextField(blank=True, null=True)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('respondent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('respondent_address', models.TextField(blank=True, null=True)),
                ('respondent_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('respondent_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('N/A', 'N/A'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='N/A', max_length=20)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Under Investigation', 'Under Investigation'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Submitted', max_length=30)),
                ('assigned_official', models.IntegerField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'complaints',
                'ordering': ['-submitted_at'],
                'managed': False,
            },
        ),
    ]
